### ISSUE TITLE
5px to much height

### ISSUE THREAD

**Issue by rugk** [lrsjng/kjua#10]
The library is great, it just adds 5 pixel to the height.

This is not bad and you add CSS styles to mitigate this issue as it seems, but a proper solution would be if the output image is really a square at the right size. :smiley:

**Comment by lrsjng** [comment]
@rugk thanks for reporting, I'm not exactly sure what you mean, could you provide an example `config` for that issue?

**Comment by rugk** [comment]
AFAIK the resulting PNG image just _never_ was a square, but actually had 5 extra px at the bottom…

**Comment by rugk** [comment]
Solved or what?

**Comment by lrsjng** [comment]
I can't see, reproduce or remember any such behavior.. can you come up with an example?

**Comment by rugk** [comment]
Yeah, cannot really reproduce (anymore :thinking:)
