### ISSUE TITLE
Object.assign is not defined in IE11

### ISSUE THREAD

**Issue by David-111** [lrsjng/kjua#11]
You need to implement an alternative for Object.assign in IE11 or lower. You can use Array.reduce, which is working for IE9 or higher.

**Comment by lrsjng** [comment]
kjua is only meant to work in modern browsers. For older browsers please have a look at https://larsjung.de/jquery-qrcode/

**Comment by martinschilliger** [comment]
@David-111 Maybe you could use [polyfill.io](https://polyfill.io/)?
