### ISSUE TITLE
Minified script contains "Function" eval

### ISSUE THREAD

**Issue by rugk** [lrsjng/kjua#14]
![image](https://user-images.githubusercontent.com/11966684/57574699-2ccdf400-743e-11e9-9856-a26e972ce4bb.png)

row 2 column 2145

v0.6.0

--

This is basically an "eval" and should never be used. (in your eslint you also disallow eval)

**Comment by lrsjng** [comment]
That was due to Webpack trying to find the "global" object, removed the reference.
