### ISSUE TITLE
Object.assign on safari 8.0.3

### ISSUE THREAD

**Issue by daggerjames** [lrsjng/kjua#2]
Some browsers, like safari 8.0.3, do not support functions like Object.assign().
Is it better to convert es6 with babel-polyfill?

**Comment by qpwr** [comment]
Well, this is a serious issue as I try to use this nice library for my cordova-based app which should also support iOS versions < 9. Is a fix planned for this?

**Comment by lrsjng** [comment]
Hi @daggerjames, @qpwr, if you want to support older browsers please use a [Object.assign polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill).
