### ISSUE TITLE
Safari throws a CORS error

### ISSUE THREAD

**Issue by mrbfrank** [lrsjng/kjua#3]
Navigate to https://larsjung.de/kjua/latest/demo/ in Safari. Refresh the page and watch the console. It seems to render fine on first load, but any subsequent page load throws the error.

**Comment by coppolaemilio** [comment]
I have the same issue with safari

**Comment by banciur** [comment]
You can switch to canvas mode 
var el = kjua({text: 'hello!', render: 'canvas'});
