### ISSUE TITLE
Different size qr code

### ISSUE THREAD

**Issue by protoror** [lrsjng/kjua#4]
I put in text vcard data and different data = different size qr code?
in previous plugin qrcode, all qrcode with  different vcard date have same size.
How see bug: first open https://larsjung.de/kjua/latest/demo/ and set 250 px size

test1
BEGIN:VCARD\r\nVERSION:2.1\r\nN:Новотекс Кострома\r\nORG:ООО «Новотекс»\r\nTEL:+74942432341\r\nADR:Кострома, ул. Московская, д. 84б, офис 1.\r\nURL:http://termoteks.ru\r\nEMAIL:sales@termoteks.ru\r\nEND:VCARD

test 2
BEGIN:VCARD\r\nVERSION:2.1\r\nN:Новотекс МО\r\nORG:ООО «Новотекс»\r\nTEL:+74955113538\r\nADR:Королёв, просп. Королёва, д. 24\r\nURL:http://termoteks.ru\r\nEMAIL:termotex-m@yandex.ru\r\nEND:VCARD

**Comment by lrsjng** [comment]
try `crisp: false`

**Comment by protoror** [comment]
thank you, it work
