### ISSUE TITLE
Generate SVG?

### ISSUE THREAD

**Issue by bambax** [lrsjng/kjua#7]
Hello,
What would be necessary to add SVG support, ie the possibility of generating svg files or svg paths, to use offline (in pdf generation for instance)?
Thank you.

**Comment by werthdavid** [comment]
I forked this repo and added SVG-rendering. It is published as kjua-svg on NPM. Feel free to try it out

**Comment by rugk** [comment]
source seems to be here: https://github.com/werthdavid/kjua

I'll take a look…

Some questions though:
1. Why not (consider to) contribute it back to upstream here? :smiley: 
2. Did you keep/support the "crisp mode" in the SVG version, too?

**Comment by rugk** [comment]
Ah okay 2. is answered [by the "limitations" sections in the Readme](https://github.com/werthdavid/kjua#limitations).

**Comment by werthdavid** [comment]
I didn’t make a PR since the owner of Kjua doesn’t seem to care. He’s not answering to issues or the other open PR and even private mails..

**Comment by rugk** [comment]
Anyway, it would be good to propose one. So you show interest at least and no one can blame you that you did not intend to contribute it back.

**Comment by werthdavid** [comment]
That’s right I’ll do that..

**Comment by werthdavid** [comment]
Crisp-mode was added

**Comment by rugk** [comment]
Awesome! I'll need to look into that, because this can solve https://github.com/rugk/offline-qr-code/issues/188 for me… :smile:  (don't mind the issue title)

**Comment by werthdavid** [comment]
I have not published this on NPM yet, still working on embedding text at least... do you need a release for your extension?

**Comment by rugk** [comment]
I can also just manually download/use the JS file, so no. 😄

**Comment by rugk** [comment]
Okay, actually a release would be nice. I use the file in `dist` usually.

**Comment by werthdavid** [comment]
Will do

**Comment by werthdavid** [comment]
kjua-svg@1.6.1
(I am willingly breaking semver since I want it to be close to kjua. so kjua 0.6 will always be a kjua-svg 1.6)

**Comment by rugk** [comment]
If this lib is really not maintained, you could just continue maintaining/versioning it as usual.

BTW 1.6.1 release is not on GitHub yet: https://github.com/werthdavid/kjua (maybe just npm?)

**Comment by rugk** [comment]
Okay, I am testing how the new lib looks in https://github.com/rugk/qr-code-libs-test/pull/2. What I've noticed so far as that the SVG version is bigger and does not add an automatic border? (still v1.6, so crisp does not work yet)

**Comment by werthdavid** [comment]
I’ve added svg.js in 1.6.2 to enable embedding of Label or Image on the SVG element. Couldn’t get it to work with plain JS, svg manipulation is a pain in the a**. 

Is this a problem? Any better ideas?

**Comment by rugk** [comment]
The new releases are still not [tagged on GitHub](https://github.com/werthdavid/kjua/releases). Anyway, I've updated my test (comparison) site and it works great!

**Comment by lrsjng** [comment]
I added a svg mode.
