### ISSUE TITLE
Resize QR code on the fly?

### ISSUE THREAD

**Issue by rugk** [lrsjng/kjua#9]
Would there be a nice way to resize the QR code "on the fly" without regenerating it? Of course, as an image that won't work, but what if a Canvas is used?

I still doubt it and think only an SVG (https://github.com/lrsjng/kjua/issues/7) would be re-sizable without any quality penalty.

**Comment by lrsjng** [comment]
Maybe the newly added svg mode might help you here in combination with CSS, otherwise I have no intention to add support for resizable codes.
